### ISSUE TITLE
Test failure

### ISSUE THREAD

**Issue by khinsen** [DrDaveShaw/INCHEM-Py#7]
Running `INCHEM_test.py` results in one failure:

```
======================================================================
ERROR: test_initial_conditions_pickle (__main__.TestInitial)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "INCHEM_test.py", line 157, in test_initial_conditions_pickle
    1,1,900,path)
  File "/Users/hinsen/Temp/INCHEM-Py/modules/initial_dictionaries.py", line 61, in initial_conditions
    index_values = in_data.index.values
  File "/Users/hinsen/anaconda3/lib/python3.6/site-packages/pandas/core/generic.py", line 5270, in __getattr__
    return object.__getattribute__(self, name)
  File "pandas/_libs/properties.pyx", line 63, in pandas._libs.properties.AxisProperty.__get__
  File "/Users/hinsen/anaconda3/lib/python3.6/site-packages/pandas/core/generic.py", line 5270, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute '_data'
```

**Comment by DrDaveShaw** [comment]
@khinsen thank you for raising this issue, I believe this is a version issue with pandas. The data file used to test the import function was created by version 1.1.3 and any version above 1.1.0 should work. Could you check/update your pandas version and confirm?

I will add a print statement to the test if this is the case.

**Comment by khinsen** [comment]
My Anaconda installation is indeed a bit old, with pandas at version 1.0.5.  I created a new environment with the current versions of everything. That means pandas 1.2.4, and with that version all tests pass.

**Comment by DrDaveShaw** [comment]
That's good news. I'll add catch for this in the `INCHEM_test` module and close the issue.

This isn't an error that causes any issues with INCHEM-Py itself as users will be creating the in_data.pickle file themselves and therefore will always have compatibility with their version of pandas.
